# Generated by Django 5.0.1 on 2024-01-03 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AZURE', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='student',
            name='fathername',
        ),
    ]
