# Generated by Django 5.0.1 on 2024-01-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AZURE', '0002_remove_student_classname_remove_student_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Onlinetraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Azure', models.CharField(max_length=1000)),
                ('AWS', models.CharField(max_length=1000)),
                ('Azuredevops', models.CharField(max_length=1000)),
                ('Jenkins', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
