# Generated by Django 5.0.1 on 2024-01-04 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AZURE', '0004_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Onlinetraining',
        ),
    ]
