apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: app1.venkateswarainstitutions.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: web-service
            port:
              number: 8000
  - host: app2.venkateswarainstitutions.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: httpd-service
            port:
              number: 8001
  - host: app3.venkateswarainstitutions.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: Django-service
            port:
              number: 8002  
  ingressClassName: nginx