apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_USER: cm9vdA==  # base64 encoded value for the MySQL user
  MYSQL_ROOT_PASSWORD: cm9vdA==  # base64 encoded value for the MySQL password


#echo -n 'hello world' | base64
#echo 'aGVsbG8gd29ybGQK' | base64 -d
